site_name: MTR 齐齐玩服务器非官方指南
site_description: 这里是由 MTR 齐齐玩服务器玩家社区搭建的非官方指南，希望你能找到你想要的内容！
site_author: LPS Community Team
site_url: https://www.lpsguide.cn

# 文档目录
docs_dir: docs
# 站点输出目录
site_dir: site

# GitHub仓库信息
repo_name: 'mtrlps-community/lps-community-guide'
repo_url: 'https://github.com/mtrlps-community/lps-community-guide'
edit_uri: 'https://github.com/mtrlps-community/lps-community-guide/edit/main/docs/'

# 语言设置
theme:
  name: material
  language: zh
  palette:
    # 浅色主题
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    # 深色主题
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.action.edit
  # logo: assets/logo.png  # TODO: 添加站点logo，建议尺寸：120x120px
  # favicon: assets/favicon.ico  # TODO: 添加站点favicon，建议尺寸：32x32px

# 导航结构
nav:
  - 首页: index.md
  - 进服教程与官方资源:
    - 进服教程: tutorial/index.md
    - 官方Wiki、线路图与世界地图: official/websites.md
    - Discord: official/discord.md
  - 社区资源:
    - 网盘资源与线路图: community/downloads.md
    - QQ 群聊: community/qq-group.md
  - 关于网站: about/about.md

# 插件
plugins:
  - search:
      lang: zh
  - git-revision-date-localized:
      enable_creation_date: true

# 扩展配置
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - toc:
      permalink: true

# 版权信息（可选）
copyright: Copyright &copy; 2026 Let's Play Server Community Team

# 扩展
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mtrlps-community
      name: GitHub
extra_javascript:
  - assets/umami.js
extra_css:
  - assets/stylesheets/global.css
